workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'

variables:
  IMAGE_NAME: kurtay/gitlab-app
  IMAGE_TAG: py-1.0

stages:
  - test
  - build
  - deploy

stage_test:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - cd app
    - pip install -r requirements.txt
  script:
    - echo "Starting to test"
    - python3 -m unittest
  when: manual
  only:
    - main
  tags:
    - prod

stage_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - echo "Starting to build"
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  when: manual
  dependencies:
    - stage_test
  only:
    - main
  tags:
    - prod

stage_deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  stage: deploy
  script:
    - echo "Starting to deploy"
    - kubectl config get-contexts
    - kubectl config use-context dakual/gitlab-ci-cd-demo:development
    - kubectl get pods
  when: manual
  dependencies:
    - stage_build
  only:
    - main
  tags:
    - prod

