apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: myapp
  type: NodePort